import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerQueryTool } from './query';
import { registerSchemaTools } from './schema';
import { registerGetCurrentDateTool } from './getCurrentDate';
import { registerGetEmpireFleetTool } from './getEmpireFleet';
import { registerGetEmpirePopulationTool } from './getEmpirePopulation';
import { registerSystemConnectionsTool } from './SystemConnectionsTool';
import { registerGetCombatLogsTools } from './getCombatLogs';
import { registerGetEmpireLogisticsTools } from './getEmpireLogistics';
import { registerGetEventLogTool } from './getEventLog';
import { registerGetResearchStatusTool } from './getResearchStatus';
import { registerGetShipyardStatusTool } from './getShipyardStatus';
import { registerGetSessionStatusTool } from './getSessionStatus';
import { registerLogContextTool } from './logContext';
import { registerGetTechTreeTool } from './getTechTree';
import { registerCalculatorTools } from './calculators';
import { registerViewTools } from './injectViews';

export const registerTools = (server: McpServer) => {
  registerQueryTool(server);
  registerSchemaTools(server);
  registerGetCurrentDateTool(server);
  registerGetEmpireFleetTool(server);
  registerGetEmpirePopulationTool(server);
  registerGetCombatLogsTools(server);
  registerGetEmpireLogisticsTools(server);
  registerSystemConnectionsTool(server);
  registerGetEventLogTool(server);
  registerGetResearchStatusTool(server);
  registerGetShipyardStatusTool(server);
  registerGetSessionStatusTool(server);
  registerLogContextTool(server);
  registerGetTechTreeTool(server);
  registerCalculatorTools(server);
  registerViewTools(server);
};
